id: IA99BAA4B
default_language: en
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:22:35.505487
last_modified: 2023-02-08 15:22:35.505643
source_metadata:
  title: Saddharmapuṇḍarīka
  language: en
bases:
  D1A8:
    base_file: D1A8.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
